In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("imss_analisis_profundo_concentrado.csv", encoding="utf-8-sig", low_memory=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17070874 entries, 0 to 17070873
Data columns (total 17 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Unnamed: 0                int64
 1   fuente                    object
 2   timestamp                 object
 3   periodo_informacion       object
 4   cve_entidad               object
 5   sexo                      object
 6   rango_edad                object
 7   rango_uma                 object
 8   sector_economico_1        object
 9   total_asegurados          float64
 10  masa_salarial_total       float64
 11  trabajadores_permanentes  float64
 12  trabajadores_eventuales   float64
 13  masa_sal_permanentes      float64
 14  masa_sal_eventuales       float64
 15  periodicidad              object
 16  comentarios               object
dtypes: float64(6), int64(1), object(10)
memory usage: 2.2+ GB

In [4]:
df.head()

,Unnamed: 0,fuente,timestamp,periodo_informacion,cve_entidad,sexo,rango_edad,rango_uma,sector_economico_1,total_asegurados,masa_salarial_total,trabajadores_permanentes,trabajadores_eventuales,masa_sal_permanentes,masa_sal_eventuales,periodicidad,comentarios
0,0,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,W2,3.0,1.0,137.18,1.0,0.0,137.18,0.00,mensual,fecha de ajuste en metodología cambio de vsm a...
1,1,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,W2,4.0,8.0,897.46,4.0,4.0,488.00,409.46,mensual,fecha de ajuste en metodología cambio de vsm a...
2,2,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,W22,9.0,1.0,1603.28,1.0,0.0,1603.28,0.00,mensual,fecha de ajuste en metodología cambio de vsm a...
3,3,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,W3,4.0,1.0,171.72,0.0,1.0,0.00,171.72,mensual,fecha de ajuste en metodología cambio de vsm a...
4,4,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,no_ligados_a_patron,no_ligados_a_patron,0.0,0.00,0.0,0.0,0.00,0.00,mensual,fecha de ajuste en metodología cambio de vsm a...

In [6]:
df['cve_entidad'].value_counts(dropna=False)

cve_entidad
9                      684050
14                     658373
19                     634383
15                     627013
30                     623470
26                     613116
8                      609324
11                     600943
5                      595317
22                     592107
28                     577985
2                      570777
25                     567300
21                     565892
16                     553336
24                     538070
10                     512818
31                     493363
13                     488467
3                      487381
27                     487051
23                     486193
7                      482096
1                      478221
4                      468226
20                     466587
32                     465077
17                     464818
6                      454431
12                     448257
18                     432488
29                     343943
no_ligados_a_patron         1
Name: count, dtype: int64

In [13]:
df["sexo"].astype("string").apply(repr).value_counts().head(30)

sexo
'1'     9559423
'2'     7510686
'3'         764
'89'          1
Name: count, dtype: int64

In [10]:
df["sexo"].astype("string").apply(repr).value_counts()

sexo
'1'     9559423
'2'     7510686
'3'         764
'89'          1
Name: count, dtype: int64

In [9]:
df["sexo"] = df["sexo"].replace({
    "no_ligados_a_patron": "89"
})

In [11]:
mask = df["sexo"] == "89"

df.loc[mask, "comentarios"] = (
    "Código 89 corresponde a derechohabientes no ligados a un patrón"
)

In [7]:
df['cve_entidad'].nunique()

33

In [5]:
df['periodicidad'] = 'mensual'

In [5]:
df.head()

,fuente,timestamp,periodo_informacion,cve_entidad,sexo,rango_edad,rango_uma,sector_economico_1,total_asegurados,masa_salarial_total,trabajadores_permanentes,trabajadores_eventuales,masa_sal_permanentes,masa_sal_eventuales,periodicidad
0,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,W2,3.0,1.0,137.18,1.0,0.0,137.18,0.00,mensual
1,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,W2,4.0,8.0,897.46,4.0,4.0,488.00,409.46,mensual
2,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,W22,9.0,1.0,1603.28,1.0,0.0,1603.28,0.00,mensual
3,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,W3,4.0,1.0,171.72,0.0,1.0,0.00,171.72,mensual
4,IMSS,2026-01-21 13:09:13,2017-02-28,1,1,E1,no_ligados_a_patron,no_ligados_a_patron,0.0,0.00,0.0,0.0,0.00,0.00,mensual

In [6]:
df['comentarios'] = ''

In [7]:
df.loc[df['periodo_informacion'] == '2017-02-28', 'comentarios'] = 'fecha de ajuste en metodología cambio de vsm a pesos'

In [8]:
df.loc[df['periodo_informacion'] == '2017-01-31', 'comentarios'] = 'hasta esta fecha el registro era en vsm'

In [9]:
# 1. Verificar las fechas corregidas
df[df['periodo_informacion'] == '2019-11-30'][['periodo_informacion', 'comentarios']]

         periodo_informacion comentarios
16832000          2019-11-30
16832001          2019-11-30
16832002          2019-11-30
16832003          2019-11-30
16832004          2019-11-30
...                      ...         ...
16950471          2019-11-30
16950472          2019-11-30
16950473          2019-11-30
16950474          2019-11-30
16950475          2019-11-30

[118476 rows x 2 columns]

In [10]:
# 3. Verificar todos los comentarios agregados
df[df['comentarios'] != ''][['periodo_informacion', 'comentarios']]

,periodo_informacion,comentarios
0,2017-02-28,fecha de ajuste en metodología cambio de vsm a...
1,2017-02-28,fecha de ajuste en metodología cambio de vsm a...
2,2017-02-28,fecha de ajuste en metodología cambio de vsm a...
3,2017-02-28,fecha de ajuste en metodología cambio de vsm a...
4,2017-02-28,fecha de ajuste en metodología cambio de vsm a...
...,...,...
12641619,2017-01-31,hasta esta fecha el registro era en vsm
12641620,2017-01-31,hasta esta fecha el registro era en vsm
12641621,2017-01-31,hasta esta fecha el registro era en vsm
12641622,2017-01-31,hasta esta fecha el registro era en vsm
12641623,2017-01-31,hasta esta fecha el registro era en vsm

In [12]:
# 4. Contar cuántas filas tienen cada comentario
df['comentarios'].value_counts()

comentarios
fecha de ajuste en metodología cambio de vsm a pesos               116921
hasta esta fecha el registro era en vsm                            109763
Código 89 corresponde a derechohabientes no ligados a un patrón         1
Name: count, dtype: int64

In [12]:
df[df['periodo_informacion'].str.contains('2019-11', na=False)][['periodo_informacion', 'comentarios']]

         periodo_informacion comentarios
16832000          2019-11-30
16832001          2019-11-30
16832002          2019-11-30
16832003          2019-11-30
16832004          2019-11-30
...                      ...         ...
16950471          2019-11-30
16950472          2019-11-30
16950473          2019-11-30
16950474          2019-11-30
16950475          2019-11-30

[118476 rows x 2 columns]

In [13]:
# Ver todos los meses únicos de 2019
df[df['periodo_informacion'].str.contains('2019', na=False)]['periodo_informacion'].unique()

array(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
       '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
       '2019-09-30', '2019-10-31', '2019-12-31', '2019-11-30'],
      dtype=object)

In [ ]:
# 5. Verificar fechas específicas con sus comentarios
df[df['periodo_informacion'].isin(['2017-02-28', '2017-01-31', '2019-11-30'])][['periodo_informacion', 'comentarios']]

In [14]:
# 6. Ver las primeras/últimas filas de la columna periodicidad
df['periodicidad'].value_counts()

periodicidad
mensual    17070874
Name: count, dtype: int64

In [15]:
# 7. Resumen rápido
print(f"Total filas con comentarios: {(df['comentarios'] != '').sum()}")
print(f"Todas las filas tienen periodicidad: {df['periodicidad'].notna().all()}")

Total filas con comentarios: 226684
Todas las filas tienen periodicidad: True

In [ ]:
# Primero verifica si las fechas existen en el formato correcto
print(df['periodo_informacion'].unique()[:20])  # Ver formato de las fechas

In [ ]:
df.columns

In [16]:
df.to_csv("imss_analisis_profundo_concentrado.csv")